### ISSUE TITLE
Reusable workflow - adding label with "'" in description causes setup job failure

### ISSUE THREAD

**Issue by mkolasinski-splunk** [splunk/addonfactory-workflow-addon-release#183]
Current implementation of labeling mechanisms is not robust enough. Adding to PR label which includes "'" character results in syntax error and failed job setup.

Related conversation on slack: https://splunk.slack.com/archives/CRTNPEZ4M/p1695906300416239
Affected workflow debug log: https://github.com/splunk/splunk-add-on-for-unix-and-linux/actions/runs/6336126451/job/17218527644

**Comment by artemrys** [comment]
Labels should not have any effect right now.
