### ISSUE TITLE
Adding random labels to any PR (including closed) triggers a workflow

### ISSUE THREAD

**Issue by mkolasinski-splunk** [splunk/addonfactory-workflow-addon-release#197]
* [ ] Figure out how to handle random workflows triggers as result of adding labels to PRs
* [x] Issue with concurrency as well - should be updated to better handle parallel jobs execution

**Comment by artemrys** [comment]
Second issue is fixed by #198.

**Comment by artemrys** [comment]
We don't run this workflow on a labeled event anymore.
