### ISSUE TITLE
reusable workflow rollout v4.17

### ISSUE THREAD

**Issue by mkolasinski-splunk** [splunk/addonfactory-workflow-addon-release#313]
- [ ] merge https://github.com/splunk/addonfactory-workflow-addon-release/pull/312
- [x] merge [cim-field-report changes](https://github.com/splunk/addonfactory-workflow-addon-release/pull/310#pullrequestreview-2268208116)
- [ ] [update appinspect-cli version in reusable wf](https://github.com/splunk/addonfactory-workflow-addon-release/pull/318)
- [ ] https://github.com/splunk/addonfactory-workflow-addon-release/pull/311
- [ ] https://github.com/splunk/addonfactory-workflow-addon-release/pull/321
- [ ] https://github.com/splunk/addonfactory-test-matrix-action/pull/176
- [ ] https://github.com/splunk/addonfactory-workflow-addon-release/pull/322

**Comment by artemrys** [comment]
@mkolasinski-splunk seems everything is done from the list, can we close this one?
